version: "3.7"
services:
  dbus:
    image: bly-dbus:1.0.0
    build:
      context: .
    init: true
    # network_mode: "host"
    restart: "no"
    volumes:
      - dbus:/var/run/dbus/vps

volumes:
  dbus: {}
